name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy README from profile repo
      run: |
        rm -rf temp_repo
        git clone https://github.com/KaSaNaa/KaSaNaa temp_repo
        cp temp_repo/README.md README.md

    - name: Commit and push README to kasanaa.github.io
      run: |
        git config --global user.name 'KaSaNaa'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git clone https://github.com/KaSaNaa/kasanaa.github.io
        cd kasanaa.github.io
        cp ../README.md README.md
        git add README.md
        git commit -m "Update README from profile"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/KaSaNaa/kasanaa.github.io HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Jekyll for GitHub Pages
      uses: actions/jekyll-build-pages@v1.0.13
      with:
        source: ./
        destination: ./_site
        token: ${{ github.token }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
        cname: kasanaa.github.io
