name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Jekyll for GitHub Pages
      uses: actions/jekyll-build-pages@v1.0.13
      with:
        # Directory where the source files reside.
        source: ./
        # Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.
        destination: ./_site
        # Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.
        # future: # optional
        # The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.
        # build_revision: # optional, default is ${{ github.sha }}
        # Verbose output
        # verbose: # optional, default is true
        # GitHub token
        token: ${{ github.token }}
          

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
